### ISSUE TITLE
Inloggen lukt maar daarna komen foutcodes waar ik geen verstand van heb

### ISSUE THREAD

**Issue by hahadmin** [lesander/magister-calendar#17]
Hallo,

Ik ben compleet nieuw in deze wereld en ben bezig om dit voor mijn dochter op te zetten. Zij moet een betere planning maken voor zichzelf en toen dacht ik dat het handig is om de huiswerkafspraken automatisch in de Google Agenda binnen te laten komen en dat zij m.b.v. kleuren aan kan geven of iets maakwerk, leerwerk of een toets is. Het gaat helemaal goed tot het laatste gedeelte, het inlezen van de gegevens. Ook het inloggen in magister lukt. Zie hieronder het resultaat.

```
C:\Users\XXX\Documents\magister>node magister-calendar.js
[*] 12:35:42 Magister Calendar v1.5.1 started.
System Time: 12:35:42
[*] 12:35:42 Using default period to fetch appointments for.
[*] 12:35:42 Determined period is:
From Wed Jun 01 2016 12:35:42 GMT+0200 (West-Europa (zomertijd))
To Fri Jun 03 2016 12:35:42 GMT+0200 (West-Europa (zomertijd)).
[*] 12:35:42 Google OAuth2 token is valid.
C:\Users\XXX\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:3441
            setSessionId(/[a-z\d-]+/.exec(r.headers["set-cookie"][0])[0]);
                                                                 ^

TypeError: Cannot read property '0' of undefined
    at C:\Users\xxx\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:3441:66
    at Request._callback (C:\Users\xxx\Documents\magister\node_modules\magister.js\lib\node\magister-node.js:5381:16)
    at Request.self.callback (C:\Users\xxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\xxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1073:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\xxx\Documents\magister\node_modules\magister.js\node_modules\request\request.js:1019:12)
    at emitNone (events.js:72:20)
```

Aangezien ik niet in deze programmaeertaal thuis, zou ik het zeer op prijs stellen als iemand mij hiermee verder kan helpen.

Met vriendelijke groet en alvast bedankt,

Marco

**Comment by lesander** [comment]
Duplicate of #16
