### ISSUE TITLE
Server lesander.me onvindbaar

### ISSUE THREAD

**Issue by Hoi123hoi** [lesander/magister-calendar#33]
Bij stap 3 moet je toestaan dat lesander.me gebruik kan maken van je google agenda en als je dan op toestaan klikt, word je doorgestuurd naar een ander pagina. Daar moet dan een code staan, maar het probleem is dat ik een foutmelding krijg. Er staat dat het openen van de pagina is mislukt omdat de server lesander.me onvindbaar is.
Wat kan ik hier aan doen?

**Comment by lesander** [comment]
Goed gevonden. Die website is al een tijdje uit de lucht. Ik zal binnenkort een vervanger online zetten. De code kan je vinden in de URL, bijvoorbeeld `https://lesander.me/gauthhelper.html?code=a/1234567#`. Dan is de code die je nodig hebt `a/1234567#`.

**Comment by lesander** [comment]
De callback url `https://lesander.github.io/magister-calendar/gauthhelper.html` geeft je nu gemakkelijk de code.

**Comment by Hoi123hoi** [comment]
Ik heb nog een vraagje. Het begin gaat goed, maar dan krijg ik een foutmelding. Zie hieronder

`[*] 13:12:10 Magister Calendar v1.8.3 started.
[*] System Time: 13:12:10, date: Thu, 31 Aug 2017 11:12:10 GMT
[*] 13:12:10 Debugging has been disabled.
[*] 13:12:10 Using default period to fetch appointments for.
[*] 13:12:10 Determined period is:
From Thu Aug 31 2017 13:12:10 GMT+0200 (CEST)
To Fri Sep 01 2017 13:12:10 GMT+0200 (CEST).
[*] 13:12:10 Google OAuth2 token has expired. Requesting a new one.
[*] 13:12:10 Updated OAuth2 token.
/Users/User/Documents/magister-calendar/node_modules/magister.js/lib/node/magister-node.js:2383
        throw new Error('school, username and password are required.');
        ^

Error: school, username and password are required.
    at new Magister (/Users/User/Documents/magister-calendar/node_modules/magister.js/lib/node/magister-node.js:2383:15)
    at magisterLogin (/Users/User/Documents/magister-calendar/magister-calendar.js:248:3)
    at Request._callback (/Users/User/Documents/magister-calendar/magister-calendar.js:237:5)
    at Request.self.callback (/Users/User/Documents/magister-calendar/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/User/Documents/magister-calendar/node_modules/request/request.js:1082:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/User/Documents/magister-calendar/node_modules/request/request.js:1009:12)`

**Comment by lesander** [comment]
Zoals je kan zien is de foutmelding `Error: school, username and password are required.` Heb je je Magister gegevens ingevuld in `config.json`?

**Comment by Hoi123hoi** [comment]
Sorry, mijn fout heb die stap over het hoofd gezien.
